### ISSUE TITLE
Automatic cache eviction to prevent memory leaks

### ISSUE THREAD

**Issue by tom-sherman** [bvaughn/suspense#9]
Just reading through the source and docs, am I right in saying that by default the cache will grow essentially forever? And it's up to the user to call `evict(key)` to remedy this?

It's not clear to me when i would actually call evict, especially since this won't currently trigger a rerender and resuspension if the value is still in use.

**Comment by bvaughn** [comment]
> Just reading through the source and docs, am I right in saying that by default the cache will grow essentially forever? And it's up to the user to call `evict(key)` to remedy this?

That it the current default, yes. This works for apps like Replay but not for everything.

> It's not clear to me when i would actually call evict, especially since this won't currently trigger a rerender and resuspension if the value is still in use.

I'm currently working on a feature branch (#7) to add a new mutation hook (`useCacheMutation`) that uses `evict` to schedule an update.

> A good default could be for the library to somehow automatically evict once the value becomes unused??? I believe this is how Tanstack Query works, but not sure how that would work here as it requires the concept of query observers. WeakRef/FinalizationRegistry maybe?

I haven't thought enough about this yet. It's in my mental "todo" but maybe it would be worth renaming this issue to focus on that specifically. React DevTools uses an LRU for this because cache keys (in that app) are just numeric ids. I had been thinking of potentially using that approach in this library.

Perhaps `WeakRef` would work but I'm not sure of the potential performance impact, nor how this would impact features like pre-fetching (e.g. could something get de-referenced between pre-fetch and subsequent render?)

**Comment by bvaughn** [comment]
Looking into what this might look like in #12

**Comment by bvaughn** [comment]
This is ready to play with in 0.0.10
